[package]
name = "ferric"
version = "0.1.0"
authors = ["Stan Papadopoulos <stan.papadopoulos@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
serde = "1.0"
serde_yaml = "0.9"
libferric = { path = "lib" }
